### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by designvoid** [co0lsky/seeding-data-in-the-testing#1]
Why is the assertion 2 here?

https://github.com/co0lsky/seeding-data-in-the-testing/blob/master/tests/Feature/UserTest.php#L27

Surely it should be 1 as User A is just following User B?

**Comment by co0lsky** [comment]
Apologies for the late reply. The user A (id=2) follows user C (id=1) in the UsersTableSeeder.

https://github.com/co0lsky/seeding-data-in-the-testing/blob/master/database/seeds/UsersTableSeeder.php#L25

**Comment by designvoid** [comment]
Ok, but the assertion is that the following count is 2 - surely the count
of the number of users being followed is 1?

If the assertion was that the ID of the user being followed then I agree it
would be 2.
